/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs.go.skincalculator;

import java.util.Iterator;
import javax.swing.ImageIcon;

/**
 *
 * @author santiago
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    //array of Float of each weapon
    private double[] floats;
    //array of prices of each weapon
    private double[] prices;
    
    public Principal() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/images/csgo-icon-42843.png")).getImage());
        this.setLocationRelativeTo(null);
        this.setTitle("CS Go SkinCalculator");
        panelError.setVisible(false);
        floats = new double[10];
        prices = new double[10];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        conditionResult = new javax.swing.JLabel();
        priceResult = new javax.swing.JLabel();
        floatResult = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        float10 = new javax.swing.JTextField();
        floatMin = new javax.swing.JTextField();
        float2 = new javax.swing.JTextField();
        float3 = new javax.swing.JTextField();
        float4 = new javax.swing.JTextField();
        float5 = new javax.swing.JTextField();
        float6 = new javax.swing.JTextField();
        float7 = new javax.swing.JTextField();
        float8 = new javax.swing.JTextField();
        float9 = new javax.swing.JTextField();
        price1 = new javax.swing.JTextField();
        price2 = new javax.swing.JTextField();
        price3 = new javax.swing.JTextField();
        price4 = new javax.swing.JTextField();
        price5 = new javax.swing.JTextField();
        price6 = new javax.swing.JTextField();
        price7 = new javax.swing.JTextField();
        price8 = new javax.swing.JTextField();
        price9 = new javax.swing.JTextField();
        price10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        float11 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        floatMax = new javax.swing.JTextField();
        panelError = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(836, 542));
        setResizable(false);
        setSize(new java.awt.Dimension(836, 542));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Skin objetive");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 102, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(260, 210));
        jPanel1.setMinimumSize(new java.awt.Dimension(260, 210));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Total price");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setText("Float result");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setText("Condition");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        conditionResult.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        conditionResult.setForeground(new java.awt.Color(255, 0, 0));
        conditionResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(conditionResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 180, 40));

        priceResult.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        priceResult.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(priceResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 130, 50));

        floatResult.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        floatResult.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(floatResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 250, 370));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Weapon ten:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Float min:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Weapon two:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Weapon three:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setText("Weapon four:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("Weapon five:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setText("Weapon six:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setText("Weapon seven:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("Weapon eight:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setText("Weapon nine:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        float10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(float10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 130, -1));

        floatMin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        floatMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floatMinActionPerformed(evt);
            }
        });
        getContentPane().add(floatMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 70, -1));

        float2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        float2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                float2ActionPerformed(evt);
            }
        });
        getContentPane().add(float2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 130, -1));

        float3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(float3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 130, -1));

        float4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(float4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 130, -1));

        float5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(float5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 130, -1));

        float6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(float6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 130, -1));

        float7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(float7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 130, -1));

        float8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(float8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 130, -1));

        float9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(float9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 130, -1));

        price1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 100, -1));

        price2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 100, -1));

        price3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(price3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 100, -1));

        price4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(price4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 100, -1));

        price5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(price5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 100, -1));

        price6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(price6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 100, -1));

        price7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(price7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 100, -1));

        price8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(price8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 100, -1));

        price9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(price9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 100, -1));

        price10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(price10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 100, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Float");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Price");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 100, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 450, 10));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("Float and price of each weapon");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel18.setText("Weapon one:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        float11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        float11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                float11ActionPerformed(evt);
            }
        });
        getContentPane().add(float11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 130, -1));

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel19.setText("Float max:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        floatMax.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        floatMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floatMaxActionPerformed(evt);
            }
        });
        getContentPane().add(floatMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 70, -1));

        panelError.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 0, 0)));
        panelError.setMaximumSize(new java.awt.Dimension(330, 100));
        panelError.setMinimumSize(new java.awt.Dimension(330, 100));
        panelError.setPreferredSize(new java.awt.Dimension(330, 100));
        panelError.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("Some fields have not been filled!");
        panelError.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, -1));

        getContentPane().add(panelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 320, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void floatMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floatMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floatMinActionPerformed

    private void float2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_float2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_float2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        //all prices of the weapons are obtained
        prices[0]=Double.parseDouble( price1.getText());
        prices[1]=Double.parseDouble( price2.getText());
        prices[2]=Double.parseDouble( price3.getText());
        prices[3]=Double.parseDouble( price4.getText());
        prices[4]=Double.parseDouble( price5.getText());
        prices[5]=Double.parseDouble( price6.getText());
        prices[6]=Double.parseDouble( price7.getText());
        prices[7]=Double.parseDouble( price8.getText());
        prices[8]=Double.parseDouble( price9.getText());
        prices[9]=Double.parseDouble( price10.getText());
        //all floats of the weapons are obtained
        floats[0]=Double.parseDouble( floatMin.getText());
        floats[1]=Double.parseDouble( float2.getText());
        floats[2]=Double.parseDouble( float3.getText());
        floats[3]=Double.parseDouble( float4.getText());
        floats[4]=Double.parseDouble( float5.getText());
        floats[5]=Double.parseDouble( float6.getText());
        floats[6]=Double.parseDouble( float7.getText());
        floats[7]=Double.parseDouble( float8.getText());
        floats[8]=Double.parseDouble( float9.getText());
        floats[9]=Double.parseDouble( float10.getText());
        
        double acumFloats=0;
        double acumPrices=0;
        
        for (int i = 0; i<10 ;i++) {
            acumFloats = acumFloats + floats[i];
            acumPrices = acumPrices + prices[i];
        }
        double floatMinValue = Double.parseDouble( floatMin.getText());
        double floatMaxValue = Double.parseDouble( floatMax.getText());
        double media = acumFloats/10;
        //double calculoFloat =(((floatMaxValue/100)-(floatMinValue/100))*media+(floatMinValue/100));
        double calculoFloat =((floatMaxValue-floatMinValue)*media+floatMinValue);
        //show the float total
        floatResult.setText(""+(calculoFloat/100000));
        //show the total price
        priceResult.setText("$"+(acumPrices/100));
        String condition = showCondition(calculoFloat/100000);
        //show the condition
        conditionResult.setText(condition);
        }catch(Exception e){
            panelError.setVisible(true);
            try{
                Thread.sleep(500);
            }catch(InterruptedException f){}
            panelError.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private String showCondition(double num){
        if (num<0.07)
            return "Factory new";
        else
            if (num<0.15)
                return "Casi nuevo";
                if (num<0.38)
                    return "Algo desgastado";
                else
                    if (num<0.44)
                        return "Bastante desgastado";
        return "Deplorable";
    }
    
    private void float11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_float11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_float11ActionPerformed

    private void floatMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floatMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floatMaxActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (doubleroduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conditionResult;
    private javax.swing.JTextField float10;
    private javax.swing.JTextField float11;
    private javax.swing.JTextField float2;
    private javax.swing.JTextField float3;
    private javax.swing.JTextField float4;
    private javax.swing.JTextField float5;
    private javax.swing.JTextField float6;
    private javax.swing.JTextField float7;
    private javax.swing.JTextField float8;
    private javax.swing.JTextField float9;
    private javax.swing.JTextField floatMax;
    private javax.swing.JTextField floatMin;
    private javax.swing.JLabel floatResult;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelError;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField price10;
    private javax.swing.JTextField price2;
    private javax.swing.JTextField price3;
    private javax.swing.JTextField price4;
    private javax.swing.JTextField price5;
    private javax.swing.JTextField price6;
    private javax.swing.JTextField price7;
    private javax.swing.JTextField price8;
    private javax.swing.JTextField price9;
    private javax.swing.JLabel priceResult;
    // End of variables declaration//GEN-END:variables
}
